### ISSUE TITLE
Viper Configuration for Config.YAML file

### ISSUE THREAD

**Issue by adesokanayo** [adesokanayo/firstgoapp#1]
```
viper.SetConfigName("config")
viper.AddConfigPath("etc/dagobah/")
viper.AddConfigPath("$HOME/.dagobah/")
viper.ReadInConfig()
```

Where will the home point to , will that be  within my project file or what location is $home on slide page 89 and 50 considering I'm using windows?

**Comment by influx6** [comment]
The $Home points to your user directory, that's your username home directory

**Comment by influx6** [comment]
Sorry for late reply

**Comment by adesokanayo** [comment]
Thanks Boss. I got past this already. I was  using .YAML instead of .yaml
for the extension, that was why It didn't see my config file.

Moving on now.
