### ISSUE TITLE
Viper does not have a Marshal function

### ISSUE THREAD

**Issue by adesokanayo** [adesokanayo/firstgoapp#2]
The presentation used a Marshal Function . However, I read effective go and did not find any function like that in viper package.  There was only Unmarshal which also makes sense in this context.  Was that a mistake from the presentation or am i missing something ?

func Fetcher() {
    var config Config
    **# err := viper.Unmarshal(&config)**
    if err != nil {
        fmt.Println(err)
    }

```
for _, feed := range config.Feeds {
    go PollFeed(feed)
}
```

}

**Comment by influx6** [comment]
It's a custom function on viper, check the source of viper
